### ISSUE TITLE
Scenario 6 - iPhone - Show Gas Stations checkbox is not getting deselect. 

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#10]
Steps:
1. Enter URL stopbystop.com
2. Open Seattle to Tacoma route.
3. Click on Filter option.
4. Try to uncheck the 'Show Restaurants' Checkbox.

Expected Result:
The checkbox should get unchecked when user clicks on it.

Actual Result:
The checkbox is not getting unchecked.

Screenshot: http://i.imgur.com/MpBMIvW.png

**Comment by AlexBulankou** [comment]
Fixed
