### ISSUE TITLE
Scenario 6 - iPhone - Specific Restaurants not getting selected from list.

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#24]
Scenario 6
Platform - iPhone
Steps:
Open route 'Seattle' to 'Tacoma'.
Click on 'Filter' option.
In Filter pop-up, Unselect the 'Restaurant'.

Expected Result:
The specific restaurant should be get selected.

Actual Result:
Not able to select the restaurant.

Screenshot: http://imgur.com/YUIpCrL

**Comment by AlexBulankou** [comment]
Cannot reproduce
