### ISSUE TITLE
Scenario 7 - iPhone - Specific Gas stations not getting selected from list.

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#25]
Scenario 7
Platform - iPhone
Steps:

Open route 'Seattle' to 'Tacoma'.
Click on 'Filter' option.
In Filter pop-up, Unselect the 'Gas Station'.

Expected Result:
The specific Gas station should be get selected.

Actual Result:
Not able to select the gas station.

Screenshot: http://imgur.com/2i4FBLS

**Comment by AlexBulankou** [comment]
Cannot reproduce. Please reactivate if it happens again.
