### ISSUE TITLE
Scenario 4 - On first Exit Restaurant's/Gas Station icon disappears after clicking/tapping back from the browser.

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#28]
Scenario - 04
Platform - iPhone, Android, Web

Steps:

Open Seattle to Tacoma route.
Click/Tap on Restaurant icon.
Click/Tap on back from the browser.
Observe the First exit icons.
Repeat same steps after tap/clicking on Gas Station icon.

Expected Result:
On first Exit Only Restaurant icon gets displayed and Gas station icon gets disappeared.

Actual Result:
Both Restaurant/Gas station icons should get displayed on first Exit.

Screenshot:

iPhone - http://imgur.com/g9nsVw8
Android - http://imgur.com/5XpWE7X
Web - http://imgur.com/Ht02uaa

**Comment by abhishek-vtest** [comment]
Still this issue is appearing in - Test Pass 20161205

**Comment by AlexBulankou** [comment]
Fixed
