### ISSUE TITLE
Scenario 2 - iphone - 'Seattle' option not displayed in drop down.

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#3]
Scenario 2 
Platform - iPhone
Steps:
Enter 'Seat' in the first text box.
Search for 'Seattle' option.

Expected Result:
'Seattle' option should be displayed in the drop-down list.

Actual Result:
'Seattle' option is not displayed in the drop-down list.

Screenshot: http://i.imgur.com/BjuZCUT.jpg

**Comment by AlexBulankou** [comment]
Cannot reproduce. Please reactivate it it happens again.
