### ISSUE TITLE
Scenario 7 - For All Platform - 'Add To Route' option is not provided in Map view.

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#34]
Scenario - 07
Platform - iPhone, Android and Web

Steps:
1. Open Seattle to Tacoma route.
2. Tap/Click on first Exit.
3. Tap/Click on 'Add to Route' for first place.
4. Scroll down and tap/click on last Exit.
5. Tap/Click on Map view icon.
6. Tap/Click on any POI.

Expected Result:
'Add to route' option should be displayed when user tap/click on any POI.

Actual Result:
'Add to route' option is not provided and other options are displayed truncated in pop-up.

Screenshot:
1. iPhone - http://i.imgur.com/qaYvyZ3.jpg
2. Android - http://i.imgur.com/ONf0TY2.png
3. Web - http://i.imgur.com/lmEKZId.png

**Comment by abhishek-vtest** [comment]
Issue still exist

**Comment by AlexBulankou** [comment]
Fixed
