### ISSUE TITLE
iPhone and Web - Scenario 8 - "Let's Go" button functionality is not working.

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#35]
Scenario - 8
Platform - iPhone and Web

Steps:
1. Enter URL Stopbystop.com.
2. Enter Current and Destination location. E.g: Seattle and Tacoma 
3. Tap/Click 'VIEW MY ROUTE' button.
4. Tap/Click on first Exit and choose first option and add to route.
5. Scroll down the screen and tap/click on last Exit, choose first option and add to route.
6. Tap/Click on 'Let's Go' button.

Expected Result:
Map should get open when user tap/click on 'Let's Go' button.

Actual Result:
No action is performed when user tap/clicks on 'Let's Go' button.

Screenshot: 
1. iPhone  - http://i.imgur.com/SpLT9P7.png
2. Web - http://i.imgur.com/lGcCGnH.png

**Comment by AlexBulankou** [comment]
Fixed. Thanks for reporting @abhishek-vtest
