### ISSUE TITLE
Scenario 4 - Yelp options are missing.

### ISSUE THREAD

**Issue by vtestcorp** [stopbystop/sbs-app#38]
Scenario - 04
Platform - iPhone, Android, Web

Steps:

  1.  Open Seattle to Tacoma route.
  2.  Tap on Gas stations icon from first exit
  3. Observe the Yelp options

Actual Result:
Yelp options are missing.

Expected Result:
Yelp options should be displayed

Screenshot:

    iPhone - http://i64.tinypic.com/2cwjtl.jpg
    Android - http://i66.tinypic.com/5nnecy.png
    Web - http://i64.tinypic.com/9ao2g2.png

**Comment by AlexBulankou** [comment]
This is now by design, as Yelp icon is displayed for some of the items, but not for all of them.
