### ISSUE TITLE
Social Marketing project Danieeel

### ISSUE THREAD

**Issue by SDanieeel** [stopbystop/sbs-app#39]
Hi there

Travel post is understood, destination post still need clarifications. Do you have a video tutorial?  I seem to get lost at step number 3 of the destinations posts. 

Payment per week for this : $ 150

![twitter quote picture](https://cloud.githubusercontent.com/assets/26932871/24716922/3f63bd72-1a39-11e7-9226-f167d51f1b62.png)

**Comment by AlexBulankou** [comment]
Thanks @SDanieeel. Really appreciate your time reviewing requirements and preparing a sample post. I'll evaluate other proposals and come back to you if I decide to go with yours.
