### ISSUE TITLE
Scenario 7 - iPhone - Specific restaurant not getting selected from list. 

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#4]
Scenario 7
Platform - iPhone
Steps:
1. Open route 'Settle' to 'Tacoma'.
2. Click on 'Filter' option.
3. In Filter pop-up, Unselect the 'Gas Station'.
4. Click on 'None' option.
5. Try to Select 'Thai' from the restaurant's list.

Expected Result:
The specific restaurant should be get selected.

Actual Result:
Not able to select the restaurant.

Screenshot: http://i.imgur.com/knc5UJ9.png

**Comment by AlexBulankou** [comment]
Fixed
