### ISSUE TITLE
"Add to route" label on place is missing.

### ISSUE THREAD

**Issue by vtestcorp** [stopbystop/sbs-app#42]
Scenario - 07
Platform - Android, Web, iPhone

Steps:

1. Open Seattle to Tacoma route.
2. Click on first exit in the road line.
3. On the exit page Observe the Add to route button.

Expected Result :
"Add to route" button should be displayed on exit page.

Actual Result :
"Add to route" label on place is missing.

Screenshots : 
Android : https://gous.tinytake.com/sf/MTYwOTMwMF81NDcwNjE3
iPhone : https://gous.tinytake.com/sf/MTYwOTMwNF81NDcwNjIx
Desktop : https://gous.tinytake.com/sf/MTYwOTMwNl81NDcwNjIz

**Comment by AlexBulankou** [comment]
By design, updated test pass template

**Comment by vtestcorp** [comment]
Can you please provide me link for updated test pass template?
