### ISSUE TITLE
"Add to rout" tooltip with place details is missing. 

### ISSUE THREAD

**Issue by vtestcorp** [stopbystop/sbs-app#43]
Scenario - 07
Platform - Android, Web, iPhone

Steps:

1. Open Seattle to Tacoma route.
2. Click on first exit in the road line.
3. On the exit page click Observe the Add to route button.
4. Click on Add to route. Route page should open.
5. On the sidebar there should be an of the pace you picked.
6. Scroll the roadline all the way down and pick the last exit.
7. On the exit page select Map view.
8. Try to Select any place.
9. Observe the result.

Expected Result :
"Add to route" tooltip with place details should be displayed when user clicks on any place.

Actual Result :
"Add to rout" tooltip with place details is missing. 

Video Link : 
https://gous.tinytake.com/sf/MTYwOTA1N181NDcwMjEw

**Comment by AlexBulankou** [comment]
By design. Updated test pass template.

**Comment by vtestcorp** [comment]
Can you please provide me link for updated test pass template?
