### ISSUE TITLE
Scenario 8 - iPhone - 'Show Gas Stations' checkbox getting unchecked without clicking on it.

### ISSUE THREAD

**Issue by abhishek-vtest** [stopbystop/sbs-app#5]
Scenario - 8
Platform - iphone
Precondition - 'Show Gas Station' checkbox should be unchecked.
Steps:
1. Open route 'Seattle' to 'Tacoma'.
2. Click on 'Filter' option.
3. Try to click on 'Show Gas Stations' checkbox.

Expected Result:
'Show Gas Stations' checkbox should not get unchecked without clicking on it.

Actual Result:
'Show Gas Stations' checkbox is getting unchecked without clicking on it.

Screenshot: http://i.imgur.com/1571Zy2.png

**Comment by AlexBulankou** [comment]
By design, session state is preserved. Will modify the scenario to include the step to open a new tab
